run:
  command: all
  data_dir: /home/toanngo/Documents/GitHub/ameriflux/ONEFlux/data
  site_id: US-ARc
  site_dir: US-ARc_sample_input
  first_year: 2005
  last_year: 2006
  prod:
  perc:
  log_file: fluxnet_pipeline_US-ARc.log
  force_py: true
  mcr_dir: /home/toanngo/Documents/GitHub/MATLAB_Runtime/v94
  timestamp:
  record_interval: hh
  version_processing:
  version_data:
  era_first_year:
  era_last_year:
  steps:
      qc_auto_execute: true
      ustar_mp_execute: true
      user_cp_execute: true
      meteo_proc_execute: true
      nee_proc_execute: true
      energy_proc_execute: true
      nee_partition_nt_execute: true
      nee_partition_dt_execute: true
      prepare_ure_execute: true
      ure_execute: true
      fluxnet2015_execute: true
      fluxnet2015_site_plots: true
      simulation: false
